### PR TITLE
Addition of induction mode

### PR DESCRIPTION
**Pull request by mabdelhack**
I added induction mode for IterativeSVD, MatrixFactorization, and SimpleFill algorithms. These would be helpful for ML algorithm training and testing. I also added a some testing modes to compare results from fit_transform and fit-then-transform.

### CODE REVIEW

**Comment by sergeyf** [comment]
Hey thanks for doing this! Looks like some nice additions. 

It looks like there's a lot of code reuse between the already-existing `solve` methods and the new `fit` methods. Can you please factor out the common parts into their own helper functions?

Also, please update the README.md to indicate which algorithms now support inductive mode.

This is optional if you feel like it: one  other approach for the `SimpleFill` is to just draw random values that already exist for the column. so `np.random.choices(X[:, col_ind])`. This works well for categorical columns.

The other question is because I am ignorant about inductive mode for IterativeSVD. Is your approach well-known - the one where you increase the rank slowly? Did you make it up?

I'll probably make more comments in the code later.

Thanks again!

**Comment by mabdelhack** [comment]
Thanks for the comments. I initially avoided changing the original code just to make sure nothing gets messed up but I think with a few modifications I can make the code more DRY.

Regarding the random mode in SimpleFill, I think we should draw a distinction because that way we are changing the dynamics of the imputation method. It will not affect categorical variables but will have a rather big effect on numerical variables (drawing from samples vs drawing from a distribution fitted to those samples) so maybe they should be different modes?

Regarding IterativeSVD, I just replicated the steps in the fit_transform method saving models at each step. I am also not that theoretically oriented so did not dig deeper into the theoretical explanation of the algorithm.

**Comment by sergeyf** [comment]
Agreed re: different modes. one mode could be `random` and one could be `random_choice`?

Thanks, the rest of your comments make sense, and the tests pass.

**Comment by mabdelhack** [comment]
Cool, I'll go for it gradually over this week

**Comment by sergeyf** [comment]
Hello any updates on this?

**Comment by mabdelhack** [comment]
Hey, sorry... I started working on it but then got occupied with other work
tasks. Will get to it as soon as time allows.

**Comment by sergeyf** [comment]
Closing. Feel free to reopen as needed.

**Pull request closed without merging**
