### PR TITLE
iterative_svd fit

### PR DESCRIPTION
**Pull request by gasper6**
I tried to make class ```iterative_svd``` support ```fit``` funcion. More testing and beautification of the code is needed, but mathematically it should work.

### CODE REVIEW

**Comment by sergeyf** [comment]
Hello, thanks for your contribution.

What is the purpose of a `fit`? You need a `transform` also, right? 

Also, please add tests to make sure that `fit` and `transform` work once you have `transform` implemented.

**Comment by sergeyf** [comment]
Hello, what's the story with this?

**Comment by gasper6** [comment]
Long story short:
I did some fixes,
dd some testing,
it didn't work well,
forgot about it.

If someone else could do testing and verify (or falsify) that my implementaton of ```transform``` is good, that would be great.

**Comment by sergeyf** [comment]
Gotcha :)

**Comment by sergeyf** [comment]
Closing. Feel free to reopen as needed.

**Pull request closed without merging**
